{{ if and (not .Values.existingSecret) (.Values.secrets) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mageai.secretName" . }}
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
stringData:
  {{ toYaml .Values.secrets | indent 2 }}
  adminEmail: {{ required "adminEmail is required." .Values.secrets.adminEmail | b64enc | quote }}
  adminPassword: {{ required "adminPassword is required." .Values.secrets.adminPassword | b64enc | quote }}
{{ end }}
